[package]
name = "abracabra"
version = "0.1.0"
authors = ["Hadrian Węgrzynowski <hadrian@hawski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adblock = "0.3.3"
chardetng = "0.1.9"
lol_html = "0.2.0"